WIP - our development
YetOpen/yii2-usuario-ldap pull request #2
Opened 2022-02-21 11:03 UTC by schmunk42

This is just for reviewing purposes, since we did a namespace change.
Please have a look and let us know if you'd basically merge these changes.

2022-02-21 13:24 UTC, maxxer commented
Hi, thanks for the PR! Honestly, I'd prefer to keep the original namespace, as we were  the original authors. Do you think this can be a problem for you?

@mp1509 do you see anything which could stop this PR from being merged, other than the NS?

2022-02-21 14:14 UTC, schmunk42 commented
> Hi, thanks for the PR! Honestly, I'd prefer to keep the original namespace, as we were the original authors.

Yeah, sure ;)

>  Do you think this can be a problem for you?

Will figure out a way to revert this if needed.

2022-02-25 07:32 UTC, maxxer commented
Please do, as said I'd prefer to retain the original NS.

Have you seen the comment on the `return` in the PR?

2022-02-25 08:42 UTC, schmunk42 commented
> Have you seen the comment on the return in the PR?

No?! In this PR?
I can't see anything here: https://github.com/YetOpen/yii2-usuario-ldap/pull/2/files

2022-02-25 09:59 UTC, maxxer commented
I don't know how to link it ;)

![immagine](https://user-images.githubusercontent.com/240201/155695241-d0402131-a5b4-4d04-97cb-37976bd1543d.png)

2022-02-25 10:27 UTC, schmunk42 commented
@maxxer Good catch! I also think your review is still in "pending" state and therefore I can not see it.

2022-02-25 10:42 UTC, maxxer requested changes

2022-02-25 10:42 UTC, maxxer commented on UsuarioLdapComponent.php
> +                Yii::debug($user, __METHOD__);return;
Is this `return` correct?

2022-10-18 16:23 UTC, schmunk42 commented
@maxxer FYI - we are actively working on that, but we need to merge your latest changes and create a new PR

CC: @eluhr @H-Algabri

2023-06-04 15:57 UTC, merged